apiVersion: v1
kind: PersistentVolume
metadata:
  name: local
  labels: 
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes: 
    - ReadWriteOnce
  hostPath: 
    path: /meubanco/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local
spec:
  storageClassName: manual
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: rhaera/db-project01:1.0
        name: mysql
        args:
        - "--ignore-db-dir=lost+found"
        imagePullPolicy: Always
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: Senha123
        - name: MYSQL_DATABASE
          value: meubanco
        ports:
        - containerPort: 3306
          name: mysql
        
        volumeMounts:
        - name: local
          mountPath: /var/lib/mysql
      volumes:
      - name: local
        persistentVolumeClaim:
          claimName: local

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - image: rhaera/backend-project01:1.0
        name: php
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        